Incorporate more EUV models
AetherModel/Aether pull request #126
Opened 2023-07-05 17:16 UTC by aaronjridley

# Description

Addresses #85 

We have incorporated the 59 wavelength model from GITM as well as the 22 wavelength model from Solomon's paper. These are included as CSV files with the right cross sections.

## Type of change

- New feature - this adds a couple more EUV models for the user to choose from.

# How Has This Been Tested?

A test has been added in tests/euv.  This tests the code in a bunch of different configurations, since EUVAC is available for all of the different wavelength files.

## Test configuration

* Operating system: Max OS 13.4; also on Linux Ubuntu
* Compiler, version number: gcc version 12.3 and 11.2
* Any details about your local setup that are relevant - didn't turn on Fortran or netCDF

# Checklist:

- [N/A] Make sure you are merging into the ``develop`` (not ``master``) branch
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (see the EUV section of the overleaf document)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

2023-07-05 20:43 UTC, aburrell requested changes

2023-07-05 20:43 UTC, aburrell commented on src/calc_ion_temperature.cpp
> +  // report.enter(function, iFunction);
Remove code instead of commenting it out, here and elsewhere.

2023-07-05 20:43 UTC, aburrell commented on tests/euv/run_test.sh
> +#!/bin/sh
Can you add a line to run this test to the yaml in `.github/workflow`?

2023-07-06 01:49 UTC, aaronjridley commented on src/calc_chemical_sources.cpp
> +      // use Tn by default
TI is more common

2023-07-06 01:54 UTC, aaronjridley commented on tests/euv/run_test.sh
> +#!/bin/sh
I don't know how to do this and I am unsure if we should have all tests run for all pull requests.  We should chat about how to do this.

2023-07-06 01:56 UTC, aaronjridley commented on src/calc_euv.cpp
> +      iErr = euv.solomon_hfg(time, indices, report);
I changed this

2023-07-06 02:07 UTC, merged

2023-07-06 15:41 UTC, aburrell commented
In the future, remember not to merge until you get an approval on the pull request.