Outputs
AetherModel/Aether pull request #72
Opened 2021-11-19 15:51 UTC by aaronjridley

# Description

Resolves #35
Resolves #50
Resolves #54
Resolves #57
Resolves #63

I have rewritten the output scheme in the code to make it more generic and streamlined. The code now uses "output containers" to allow a user/developer to fill up a container, and then call a write function on the container.  The user/developer doesn't have to write code on outputting netcdf or binary files at all, the just load their variables into the OutputContainer class, and then use the write() method.  This should make the code much easier to use.

I then implemented the containers on the restart files. So, the code now uses OutputContainers to write and read the restart files (grid, neutral, ion). I had to write a reader for the netcdf files, so it will load a netcdf file into an OutputContainer, which the code can then transfer into the appropriate variables. There are both set and get methods for the output containers for writing and reading variables.

This was primarily done to make it so DART can read the Aether restart files, so they need to be netCDF variables, but adds a bunch of functionality onto the code.

If someone wants to add a new output file type, the developer can just write an output method on the OutputContainer, and they don't have to worry about which variables are actually needed to be written. 

See note below about ramifications for aetherpy. (dependent changes)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change that adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Go into tests/restarts and run run_test.sh.  This test will run the code as a whole run and will run it with a run that has a restart.  Since the code uses netcdf as the restart files, it tests the functionality.

## Test configuration

* Operating system: Mac OSX
* Compiler, version number: gcc 10. 
* Any details about your local setup that are relevant: I had to install netcdfs in a "special way" to get them to compile with the code on Mac OSX. This is because every installer wants to use clang++ and not g++, so even downloading and installing netcdf yourself doesn't work well (the cmake defaults to clang++, and it is hard to get all of the dependencies to work with g++ - total pain).  But, you can get port to install a g++ version of netcdf, which is what I did.

# Checklist:

- [N/A] Make sure you are merging into the ``develop`` (not ``master``) branch
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules - I have pushed my changes in aetherpy to the "aaron" branch, which is my general development branch on aetherpy.  This is primarily because people wanted the variable names and units to be changed in the netCDF files and not because of MY changes.  This is fixing the issues that were introduced by this standardization.  So, to test the code, you have to use the "aaron" branch of aetherpy.
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

2021-11-19 19:15 UTC, qalshidi requested changes
Let me know what you think :).

2021-11-19 19:15 UTC, qalshidi commented on include/output.h
> +
I think not having an empty line between doxygen comment and class is how it needs to be. I might be mistaken, but I recommend it anyway as it will make the blocking more clear.

2021-11-19 19:15 UTC, qalshidi commented on include/output.h
> +
Aaron, I recommend passing the references `int output(Neutrals& neutrals,` in this case as it would speed up the code. Copying over a `Neutrals` object might not be what we're looking for here, unless you think output will be running at the same time the `Neutrals` object changes due to race conditions. My suggestion when it comes to C++ code is to do things like this `int output(const Neutrals& neutrals,` as it makes clear the Neutrals will not change in this function (because it shouldn't) and avoids bugs if someone does try to change it in this function in the future.

2021-11-19 20:03 UTC, aaronjridley commented on include/output.h
> +
I took out a couple of the spaces within the comment, but not after the comment.  I like having the space there, so the class is clearly seen when reading the code.

2021-11-19 20:06 UTC, aaronjridley commented on include/output.h
> +
I implemented this with the neutrals, ions, grid, planets, while the rest are left alone.

2021-11-23 23:00 UTC, Ionospheres commented
I'm about halfway through testing and reviewing this pull request. I noticed that the output netcdf files are not compatible with panoply anymore. When merged, will that capability be restored?

2021-11-23 23:17 UTC, aaronjridley commented
Can you point me to the exact names that you would like?  Those must not have existed in the develop branch. I can change these names super easily.  What else needs to be implemented besides the names?

2021-11-24 14:26 UTC, Ionospheres commented
I think there is some miss-match in the size of lat/lon in it's metadata description, as viewed via panoply. One is listed as 2D and the other is listed as 1D.
Thus when I try to plot it in panoply for a quick look it can't. When I directly plot Aether outputs in matlab everything works fine so the data in the output files are sized correctly. A few pull requests ago we had a fix for this and I can't remember what it was. 
   On Tuesday, November 23, 2021, 06:18:09 PM EST, Aaron Ridley ***@***.***> wrote:  
 
 


Can you point me to the exact names that you would like? Those must not have existed in the develop branch. I can change these names super easily. What else needs to be implemented besides the names?


—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-17 13:22 UTC, aaronjridley commented
Ok.  I am now about to do a pull request for the next thing that builds off of this.  It has been a month.

2022-01-10 21:46 UTC, aaronjridley commented
All, I have addressed all of the requested changes.  The last comment was 24 days ago (made by me).  Can someone please approve this so that I can then merge the mpi branch also?  Thanks!

2022-01-10 22:25 UTC, Ionospheres commented
Have you had a chance to look at why the netcdf output files think longitude is a 1D parameter? I haven't found a solution to suggest yet. Re-implementing the old fix doesn't work anymore as things have evolved from then.

2022-01-10 22:33 UTC, aaronjridley commented
I guess I have two thoughts on this: (1) I didn't realize that I was supposed to look at this, and I am not quite sure how I would test this - I probably have to figure out how to download the visualization software or whatever and then test it? Not sure. (2) I had thought that someone (maybe Ben? maybe Qusai?) mentioned that it could be that longitude needs to be capitalized. That may have been said in passing...? Can you figure this out and commit something if this is an issue that we care about?

2022-01-10 23:05 UTC, Ionospheres commented
If you want panoply you can download it from nasa here: https://www.giss.nasa.gov/tools/panoply/download/

Once you download/install it, you double click on the netcdf file you want to view and then double click on the variable (in the table that pops up) you want to plot, click OK on the pop up box of plot options, and ta-da! with five clicks of the mouse you get a Lat/Lon color plot of whatever variable you picked overlaying the continent outlines. Further customization of the plot can be done as well with additional menu selections.

We care about this compatibility issue. I'm comfortable approving this pull request though while we keep working on developing a permanent solution.  @johnsonbk Have you had any luck getting the outputs compatible with panoply again?

2022-01-10 23:08 UTC, Ionospheres approved these changes
Code runs well and performs as expected.

Panoply compatibility issue will be addressed in a future commit.

2022-01-11 12:33 UTC, merged