Mpi
AetherModel/Aether pull request #73
Opened 2021-12-29 02:41 UTC by aaronjridley

# Description

Resolves #33 
Resolves #34 
Resolves #11 

Added mpi, perturbing the indices (proper treatment of seeds), and message passing of the neutrals (for starts).

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change that adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

The default run aether.json file expects 4 processors by default.  Added example input file for ensembles and perturbing.

## Test configuration

* Operating system: Mac OSX and Ubuntu
* Compiler, version number: gcc v10

# Checklist:

- [N/A] Make sure you are merging into the ``develop`` (not ``master``) branch
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

2022-01-03 19:10 UTC, Ionospheres commented on src/init_parallel.cpp
> +  }
Can we add a "stop" here if the number of processors is not set correctly? Otherwise, it will try to write the initial output file(s), which doesn't work, and then hang indefinitely.

2022-01-04 17:39 UTC, Ionospheres requested changes
Other than adding a "stop" to prevent the code from hanging when the wrong number of processors is used, the functionality of this code looks good to me.

2022-01-18 15:01 UTC, Ionospheres commented
The "stop" when too few processers are used works great!
When I use too many processers it either crashes instead of stopping nicely or gives me more members than I specified in the json input file. For example if I set it up to have 2 members and a 2x2 grid but run with 16 processors I get output files from 4 members. Weird.

2022-01-18 15:41 UTC, aaronjridley commented
Ok, I implemented (1). We can implement something else later if we want.  I am not sure that we should. So, this is a fine fix.

2022-01-18 15:51 UTC, Ionospheres approved these changes

2022-01-18 15:52 UTC, Ionospheres commented
Looks good!

2022-01-18 15:52 UTC, merged